---
model: ddm
config_save_folder: '/users/afengler/data/proj_ak_lan/akili/data/data_generator_configs/'
generator_approach: 'lan'
data_generator_arg_dict:
    dgp_list: ddm
    n_samples: 200000
    n_parameter_sets: 5000
    delta_t: 0.001
    n_training_samples_by_parameter_set: 2000
    n_subruns: 20
model_config_arg_dict: 
---


    